spring.application.name=demo

# Stringa di connessione specifica per MariaDB (nota jdbc:mariadb invece di jdbc:mysql)
spring.datasource.url=jdbc:mariadb://localhost:3306/dipendenti_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Inizializzazione dello schema
spring.sql.init.mode=always